[
    {
        "wakeUp": 540,
        "goToSleep": 0,
        "learning": 6,
        "sports": 0,
        "cooking": 3,
        "distance": 2,
        "money": 150,
        "date": 1685923200,
        "arePenaltiesApply": false,
        "id": "old-12"
    },
    {
        "wakeUp": 540,
        "goToSleep": 60,
        "learning": 1,
        "sports": 0,
        "cooking": 3,
        "distance": 2,
        "money": 100,
        "date": 1685836800,
        "arePenaltiesApply": false,
        "id": "old-11"
    },
    {
        "wakeUp": 540,
        "goToSleep": 30,
        "learning": 2,
        "sports": 0,
        "cooking": 3,
        "distance": 2,
        "money": 110,
        "date": 1685750400,
        "arePenaltiesApply": false,
        "id": "old-10"
    },
    {
        "wakeUp": 540,
        "goToSleep": 0,
        "learning": 5,
        "sports": 0,
        "cooking": 3,
        "distance": 2,
        "money": 140,
        "date": 1685664000,
        "arePenaltiesApply": false,
        "id": "old-9"
    },
    {
        "wakeUp": 510,
        "goToSleep": 0,
        "learning": 0,
        "sports": 0,
        "cooking": 1,
        "distance": 4,
        "money": 30,
        "date": 1685577600,
        "arePenaltiesApply": true,
        "id": "old-8"
    },
    {
        "wakeUp": 450,
        "goToSleep": 0,
        "learning": 0,
        "sports": 1,
        "cooking": 0,
        "distance": 4,
        "money": 110,
        "date": 1685491200,
        "arePenaltiesApply": true,
        "id": "old-7"
    },
    {
        "wakeUp": 480,
        "goToSleep": 1410,
        "learning": 0,
        "sports": 0,
        "cooking": 0,
        "distance": 5,
        "money": 20,
        "date": 1685404800,
        "arePenaltiesApply": true,
        "id": "old-6"
    },
    {
        "wakeUp": 480,
        "goToSleep": 0,
        "learning": 0,
        "sports": 1,
        "cooking": 0,
        "distance": 4.5,
        "money": 110,
        "date": 1685318400,
        "arePenaltiesApply": true,
        "id": "old-5"
    },
    {
        "wakeUp": 510,
        "goToSleep": 0,
        "learning": 2,
        "sports": 1,
        "cooking": 0,
        "distance": 4.5,
        "money": 160,
        "date": 1685232000,
        "arePenaltiesApply": true,
        "id": "old-4"
    },
    {
        "wakeUp": 540,
        "goToSleep": 0,
        "learning": 0,
        "sports": 0,
        "cooking": 0,
        "distance": 3,
        "money": 60,
        "date": 1685145600,
        "arePenaltiesApply": true,
        "id": "old-3"
    },
    {
        "wakeUp": 540,
        "goToSleep": 1410,
        "learning": 6,
        "sports": 1,
        "cooking": 3,
        "distance": 4,
        "money": 230,
        "date": 1685059200,
        "arePenaltiesApply": true,
        "id": "old-2"
    },
    {
        "wakeUp": 540,
        "goToSleep": 0,
        "learning": 6,
        "sports": 1,
        "cooking": 3,
        "distance": 4,
        "money": 230,
        "date": 1684972800,
        "arePenaltiesApply": true,
        "id": "old-1"
    },  
    {
        "wakeUp": 540,
        "goToSleep": 60,
        "learning": 0,
        "sports": 0,
        "cooking": 0,
        "distance": 0,
        "money": 0,
        "date": 1686009600,
        "arePenaltiesApply": false,
        "id": "1"
    }
]

export {}